### ISSUE TITLE
QA: Force update location

### ISSUE THREAD

**Issue by woopstar** [gcobb321/icloud3_v3_docs#1]
Using the new iCloud v3, is this the correct way to force update the location of a device:

```
  - service: icloud3.action
    data:
      command: Send Locate Request to iOS App
      device_name: c403383c538f2dde50b21d2c557f8acb
```

I was earlier using the following to do so from automation:
```
  - service: icloud3.update
    data:
      device_name: ak_watch_icloud3
      command: location
```

**Comment by gcobb321** [comment]
The second one is correct. iCloud3 uses the actual device_name and command to know what to do.

**Comment by woopstar** [comment]
According to the documentation here: https://gcobb321.github.io/icloud3_v3/#/chapters/4.1-service-calls?id=example-automations-or-scripts

The command should be `locate` and not `location` as in the former version of iCloud3? Correct?

**Comment by gcobb321** [comment]
I just looked at the sample automations in the User Guide after not reviewing them for HA changes in a long time and I need to update them to confirm to the new standards. To answer your question, yes it was changed to _locate_. 

Here is on at works:
```
alias: iCloud3 Locate (Gary)
trigger: []
condition: []
action:
  - service: icloud3.action
    data:
      command: locate
      device_name: gary_iphone
mode: single
```
